# A generic, single database configuration for Alembic.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# max length of characters to apply to the "slug" field
truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command
revision_environment = false

# version path separator
version_path_separator = os

# Postgres connection string for the college_db_orm database.
# Update the username / password / host / port to match your setup.
sqlalchemy.url = postgresql+psycopg2://postgres:your_password@localhost:5432/college_db_orm


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts. Left empty here.


# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
